import { createServiceSupabase } from '@/lib/supabase/server';

/**
 * Lead Pipeline + CRM data access layer (Wave 6 Phase 1).
 *
 * Architecture: see DECISIONS.md Session 2 (C1-C8).
 *
 * All functions in this file use the **service-role** client and therefore
 * bypass RLS. Callers must be authenticated admin paths — never expose any
 * of these directly to a public route handler without an explicit auth
 * check on the caller side.
 */

export type LeadSource =
  | 'pipeline'         // generated by Phase 2 scrapers
  | 'service_wizard'   // form submission on /service-wizard
  | 'supply_rfq'       // form submission on /supply-wizard / product modal / list modal
  | 'manual'           // admin-typed entry
  | 'email';           // forwarded mailbox

export type LeadTrack = 'service' | 'supply';

export type LeadStage =
  | 'new'
  | 'contacted'
  | 'replied'
  | 'quoting'
  | 'won'
  | 'lost';

export type InboundChannel = 'email' | 'form' | 'whatsapp';

export type Company = {
  id: string;
  name: string;
  country: string | null;
  imo_company_no: string | null;
  website: string | null;
  contact_email: string | null;
  contact_phone: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type Vessel = {
  id: string;
  company_id: string | null;
  name: string;
  imo_no: string | null;
  vessel_type: string | null;
  year_built: number | null;
  flag: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
};

export type Lead = {
  id: string;
  company_id: string | null;
  vessel_id: string | null;
  source: LeadSource;
  track: LeadTrack;
  stage: LeadStage;
  priority_score: number;
  priority_reason: Record<string, unknown>;
  draft_message: string | null;
  assigned_to: string | null;
  context: Record<string, unknown>;
  created_at: string;
  updated_at: string;
};

export type LeadWithRefs = Lead & {
  company: Company | null;
  vessel: Vessel | null;
};

export type LeadNote = {
  id: string;
  lead_id: string;
  author: string | null;
  body: string;
  created_at: string;
};

export type LeadEvent = {
  id: string;
  lead_id: string;
  event_type: string;
  detail: Record<string, unknown>;
  created_at: string;
};

export type InboundMessage = {
  id: string;
  lead_id: string | null;
  channel: InboundChannel;
  subject: string | null;
  body: string | null;
  attachments: unknown[];
  received_at: string;
};

// =====================================================================
// READ
// =====================================================================

export async function listLeads(opts: {
  track?: LeadTrack;
  stage?: LeadStage | LeadStage[];
  source?: LeadSource;
  search?: string;
  limit?: number;
} = {}): Promise<LeadWithRefs[]> {
  const sb = createServiceSupabase();
  let q = sb
    .from('leads')
    .select('*, company:companies(*), vessel:vessels(*)')
    .order('priority_score', { ascending: false })
    .order('created_at', { ascending: false })
    .limit(opts.limit ?? 200);

  if (opts.track) q = q.eq('track', opts.track);
  if (opts.source) q = q.eq('source', opts.source);
  if (opts.stage) {
    if (Array.isArray(opts.stage)) q = q.in('stage', opts.stage);
    else q = q.eq('stage', opts.stage);
  }

  const { data, error } = await q;
  if (error) {
    console.error('[crm] listLeads error', error);
    return [];
  }
  const rows = (data ?? []) as unknown as LeadWithRefs[];

  // Client-side filter for search (Postgres full-text is over-kill at this
  // size; a few hundred rows in memory are fine until Phase 2 volume hits).
  if (opts.search && opts.search.trim()) {
    const needle = opts.search.toLowerCase().trim();
    return rows.filter((l) => {
      const haystack = [
        l.company?.name,
        l.vessel?.name,
        l.vessel?.imo_no,
        l.draft_message,
        JSON.stringify(l.context ?? {})
      ]
        .filter(Boolean)
        .join(' ')
        .toLowerCase();
      return haystack.includes(needle);
    });
  }

  return rows;
}

export async function getLead(id: string): Promise<LeadWithRefs | null> {
  const sb = createServiceSupabase();
  const { data, error } = await sb
    .from('leads')
    .select('*, company:companies(*), vessel:vessels(*)')
    .eq('id', id)
    .single();
  if (error || !data) return null;
  return data as unknown as LeadWithRefs;
}

export async function getLeadNotes(leadId: string): Promise<LeadNote[]> {
  const sb = createServiceSupabase();
  const { data } = await sb
    .from('lead_notes')
    .select('*')
    .eq('lead_id', leadId)
    .order('created_at', { ascending: false });
  return (data ?? []) as LeadNote[];
}

export async function getLeadEvents(leadId: string): Promise<LeadEvent[]> {
  const sb = createServiceSupabase();
  const { data } = await sb
    .from('lead_events')
    .select('*')
    .eq('lead_id', leadId)
    .order('created_at', { ascending: false });
  return (data ?? []) as LeadEvent[];
}

export async function leadCounts(): Promise<{
  total: number;
  byStage: Record<LeadStage, number>;
  byTrack: Record<LeadTrack, number>;
  newThisWeek: number;
}> {
  const sb = createServiceSupabase();
  const since = new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString();

  const [total, newCount, contacted, replied, quoting, won, lost, svc, sup, newWeek] =
    await Promise.all([
      sb.from('leads').select('id', { count: 'exact', head: true }),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('stage', 'new'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('stage', 'contacted'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('stage', 'replied'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('stage', 'quoting'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('stage', 'won'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('stage', 'lost'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('track', 'service'),
      sb.from('leads').select('id', { count: 'exact', head: true }).eq('track', 'supply'),
      sb
        .from('leads')
        .select('id', { count: 'exact', head: true })
        .gte('created_at', since)
    ]);

  return {
    total: total.count ?? 0,
    byStage: {
      new:       newCount.count ?? 0,
      contacted: contacted.count ?? 0,
      replied:   replied.count ?? 0,
      quoting:   quoting.count ?? 0,
      won:       won.count ?? 0,
      lost:      lost.count ?? 0
    },
    byTrack: {
      service: svc.count ?? 0,
      supply:  sup.count ?? 0
    },
    newThisWeek: newWeek.count ?? 0
  };
}

// =====================================================================
// WRITE — upserts + event recorders
// =====================================================================

/** Upsert a company by name (case-insensitive). Returns the company row. */
export async function upsertCompany(input: {
  name: string;
  country?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
}): Promise<Company> {
  const sb = createServiceSupabase();
  const trimmed = input.name.trim();

  // Look up case-insensitively
  const { data: existing } = await sb
    .from('companies')
    .select('*')
    .ilike('name', trimmed)
    .limit(1)
    .maybeSingle();

  if (existing) return existing as Company;

  const { data, error } = await sb
    .from('companies')
    .insert({
      name: trimmed,
      country: input.country ?? null,
      contact_email: input.contact_email ?? null,
      contact_phone: input.contact_phone ?? null
    })
    .select()
    .single();

  if (error) throw new Error(`upsertCompany: ${error.message}`);
  return data as Company;
}

/**
 * Upsert a vessel by IMO number (C8). If imo_no is missing, falls back to a
 * fuzzy name+company match; if neither found, inserts a stub row.
 */
export async function upsertVessel(input: {
  name: string;
  imo_no?: string | null;
  company_id?: string | null;
  vessel_type?: string | null;
  flag?: string | null;
}): Promise<Vessel> {
  const sb = createServiceSupabase();
  const trimmedName = input.name.trim();
  const trimmedImo = input.imo_no?.toString().trim() || null;

  if (trimmedImo) {
    const { data: existingByImo } = await sb
      .from('vessels')
      .select('*')
      .eq('imo_no', trimmedImo)
      .maybeSingle();
    if (existingByImo) return existingByImo as Vessel;
  }

  if (input.company_id) {
    const { data: existingByName } = await sb
      .from('vessels')
      .select('*')
      .eq('company_id', input.company_id)
      .ilike('name', trimmedName)
      .limit(1)
      .maybeSingle();
    if (existingByName) return existingByName as Vessel;
  }

  const { data, error } = await sb
    .from('vessels')
    .insert({
      name: trimmedName,
      imo_no: trimmedImo,
      company_id: input.company_id ?? null,
      vessel_type: input.vessel_type ?? null,
      flag: input.flag ?? null
    })
    .select()
    .single();
  if (error) throw new Error(`upsertVessel: ${error.message}`);
  return data as Vessel;
}

/** Create a new lead. Also writes a stage_change event for the initial state. */
export async function createLead(input: {
  source: LeadSource;
  track: LeadTrack;
  company_id?: string | null;
  vessel_id?: string | null;
  priority_score?: number;
  priority_reason?: Record<string, unknown>;
  draft_message?: string | null;
  context?: Record<string, unknown>;
}): Promise<Lead> {
  const sb = createServiceSupabase();
  const { data, error } = await sb
    .from('leads')
    .insert({
      source: input.source,
      track: input.track,
      company_id: input.company_id ?? null,
      vessel_id: input.vessel_id ?? null,
      priority_score: input.priority_score ?? 0,
      priority_reason: input.priority_reason ?? {},
      draft_message: input.draft_message ?? null,
      context: input.context ?? {}
    })
    .select()
    .single();
  if (error) throw new Error(`createLead: ${error.message}`);
  const lead = data as Lead;
  await recordEvent(lead.id, 'created', { source: input.source, track: input.track });
  return lead;
}

export async function updateLeadStage(
  id: string,
  stage: LeadStage,
  actor?: string
): Promise<Lead | null> {
  const sb = createServiceSupabase();
  const { data: before } = await sb.from('leads').select('stage').eq('id', id).single();
  const { data, error } = await sb
    .from('leads')
    .update({ stage })
    .eq('id', id)
    .select()
    .single();
  if (error) return null;
  await recordEvent(id, 'stage_change', {
    from: before?.stage ?? null,
    to: stage,
    actor: actor ?? null
  });
  return data as Lead;
}

export async function updateLeadDraft(id: string, draft: string): Promise<void> {
  const sb = createServiceSupabase();
  await sb.from('leads').update({ draft_message: draft }).eq('id', id);
}

export async function addLeadNote(input: {
  lead_id: string;
  author?: string | null;
  body: string;
}): Promise<LeadNote> {
  const sb = createServiceSupabase();
  const { data, error } = await sb
    .from('lead_notes')
    .insert(input)
    .select()
    .single();
  if (error) throw new Error(`addLeadNote: ${error.message}`);
  await recordEvent(input.lead_id, 'note_added', { author: input.author ?? null });
  return data as LeadNote;
}

export async function recordEvent(
  leadId: string,
  eventType: string,
  detail: Record<string, unknown> = {}
): Promise<void> {
  const sb = createServiceSupabase();
  await sb.from('lead_events').insert({
    lead_id: leadId,
    event_type: eventType,
    detail
  });
}

export async function recordInboundMessage(input: {
  lead_id?: string | null;
  channel: InboundChannel;
  subject?: string | null;
  body?: string | null;
  attachments?: unknown[];
}): Promise<InboundMessage> {
  const sb = createServiceSupabase();
  const { data, error } = await sb
    .from('inbound_messages')
    .insert({
      lead_id: input.lead_id ?? null,
      channel: input.channel,
      subject: input.subject ?? null,
      body: input.body ?? null,
      attachments: input.attachments ?? []
    })
    .select()
    .single();
  if (error) throw new Error(`recordInboundMessage: ${error.message}`);
  if (input.lead_id) {
    await recordEvent(input.lead_id, 'rfq_received', { channel: input.channel });
  }
  return data as InboundMessage;
}

// =====================================================================
// Inbound ingestion — used by /api/service-request + /api/quote-request
// =====================================================================

/**
 * Ingest an inbound form submission into the CRM.
 * - Upserts the company (by name) and vessel (by IMO)
 * - Creates a new lead in stage='new'
 * - Records an inbound_messages row with the raw payload as the body
 *
 * Failures are swallowed and logged — the main RFQ/service request flow
 * must not break if the CRM write fails (the request still lands in
 * rfq_requests / service_requests, which is the canonical record).
 */
export async function ingestInboundForm(input: {
  source: 'service_wizard' | 'supply_rfq';
  track: LeadTrack;
  contact_name?: string | null;
  contact_email?: string | null;
  contact_phone?: string | null;
  company_name?: string | null;
  vessel_name?: string | null;
  imo?: string | null;
  port?: string | null;
  urgency?: string | null;
  system?: string | null;
  brand?: string | null;
  part_number?: string | null;
  description?: string | null;
  raw_payload?: Record<string, unknown>;
}): Promise<{ lead_id: string | null }> {
  try {
    let company: Company | null = null;
    if (input.company_name?.trim()) {
      company = await upsertCompany({
        name: input.company_name,
        contact_email: input.contact_email ?? null,
        contact_phone: input.contact_phone ?? null
      });
    } else if (input.contact_email) {
      // Fallback: use email domain as proxy company
      const proxy = (input.contact_email.split('@')[1] ?? input.contact_email).split('.')[0];
      if (proxy) {
        company = await upsertCompany({
          name: proxy.charAt(0).toUpperCase() + proxy.slice(1),
          contact_email: input.contact_email
        });
      }
    }

    let vessel: Vessel | null = null;
    if (input.vessel_name?.trim() || input.imo?.trim()) {
      vessel = await upsertVessel({
        name: input.vessel_name?.trim() || 'Unknown vessel',
        imo_no: input.imo?.trim() || null,
        company_id: company?.id ?? null
      });
    }

    const context: Record<string, unknown> = {};
    if (input.port) context.port = input.port;
    if (input.urgency) context.urgency = input.urgency;
    if (input.system) context.system = input.system;
    if (input.brand) context.brand = input.brand;
    if (input.part_number) context.part_number = input.part_number;
    if (input.contact_name) context.contact_name = input.contact_name;
    if (input.contact_email) context.contact_email = input.contact_email;
    if (input.contact_phone) context.contact_phone = input.contact_phone;
    if (input.description) context.description = input.description;

    const priority_score = priorityScoreForInbound(input.urgency, input.track);

    const lead = await createLead({
      source: input.source,
      track: input.track,
      company_id: company?.id ?? null,
      vessel_id: vessel?.id ?? null,
      priority_score,
      priority_reason: { reason: 'inbound', urgency: input.urgency ?? null },
      context
    });

    await recordInboundMessage({
      lead_id: lead.id,
      channel: 'form',
      subject: summariseForm(input),
      body: JSON.stringify(input.raw_payload ?? input, null, 2)
    });

    return { lead_id: lead.id };
  } catch (e) {
    console.error('[crm] ingestInboundForm failed', e);
    return { lead_id: null };
  }
}

function summariseForm(input: {
  vessel_name?: string | null;
  imo?: string | null;
  port?: string | null;
  system?: string | null;
  brand?: string | null;
  part_number?: string | null;
  track: LeadTrack;
}): string {
  const bits: string[] = [];
  bits.push(input.track === 'service' ? 'Service request' : 'Supply RFQ');
  if (input.system) bits.push(input.system);
  if (input.brand) bits.push(input.brand);
  if (input.part_number) bits.push(input.part_number);
  if (input.vessel_name) bits.push(`vessel: ${input.vessel_name}`);
  if (input.imo) bits.push(`IMO ${input.imo}`);
  if (input.port) bits.push(`@ ${input.port}`);
  return bits.join(' · ');
}

/** Coarse first-pass scoring for inbound leads. Real model lives in Phase 2. */
function priorityScoreForInbound(urgency: string | null | undefined, track: LeadTrack): number {
  const u = (urgency ?? '').toLowerCase();
  if (u === 'aog' || u === 'now' || u === 'emergency') return 90;
  if (u === '24h' || u === 'urgent') return 70;
  if (track === 'service') return 50;
  return 40;
}

export function stageLabel(stage: LeadStage, locale: Locale = 'en'): string {
  const map = {
    en: { new: 'New', contacted: 'Contacted', replied: 'Replied', quoting: 'Quoting', won: 'Won', lost: 'Lost' },
    tr: { new: 'Yeni', contacted: 'İletildi', replied: 'Yanıtlandı', quoting: 'Teklif', won: 'Kazandı', lost: 'Kayıp' }
  } as const;
  return (map[locale as keyof typeof map] ?? map.en)[stage];
}

export function sourceLabel(src: LeadSource): string {
  return {
    pipeline:       'Pipeline',
    service_wizard: 'Service form',
    supply_rfq:     'Supply RFQ',
    manual:         'Manual',
    email:          'Email'
  }[src];
}

export const STAGE_ORDER: LeadStage[] = ['new', 'contacted', 'replied', 'quoting', 'won', 'lost'];
